* Small blog
  made for ease of use and portability, many places you cant get a hold
  of a database, but most sites gives you php and usually with sqlite.

  The security should be ok, as long as you set the permissions right,
  and also keep strict .htacces for geting a hold of .conf (the db only
  stores the blog titles and content, so read-access there should not do
  much).

* setup
  rename .conf.php.example to .conf.php and hash a password, on the command
  line: 
  - "hash('sha512', hash('sha512', 'yourpasswordhere'));"
  
  check access to .conf and the rest of the files, and you're good to go.
* UiO
  For some reason I had to keep the whole folder for the db rwx(777), the upside is that
  the db don't have to be that open. So I made a new folder to set it up there.

  .php files should be kept at r only (444) ofc, would've liked less but... other than that things kan be kept
  at 755 :) hope it works.
* i18n
  everything is in index.html, it should be an easy job to translate it :)
